# Generated by Django 5.0.3 on 2024-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment_List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
